import React, {useId} from 'react'

function Select({
    options, //An array of values to populate the dropdown.
    label,   //Optional label text for the dropdown.
    className, 
    ...props  //Any other props that should be passed to the select element.
}, ref) {   //reference for the <select> element, enabling parent components to interact with it directly.
    const id = useId()
 
    return (
    <div className='w-full'>
        {label && <label htmlFor={id} className=''></label>}
        <select {...props} id={id} ref={ref}
        className={`px-3 py-2 rounded-lg bg-white text-black outline-none focus:bg-gray-50 duration-200 border border-gray-200 w-full 
        ${className}`}>
            {options?.map((option) => (
                <option key={option} value={option}>
                    {option}
                </option>
            ))}
        </select>
    </div>
  )
}

export default React.forwardRef(Select)

//Select component is a simple select component that takes in options and renders them as options in a select element.
//It also takes in a label and a className prop. The label prop is used to render a label element for the select element.
//The className prop is used to add additional classes to the select element.
//The useId hook is used to generate a unique id for the select element.
//Conditionally renders the <label> element if a label prop is provided.
//The htmlFor={id} associates the label with the <select> element using the unique ID generated by useId.
//Select element is rendered with dropdown options based on the options prop.
//Iterates over the options array and renders an <option> element for each value.
//The key prop is set to the option value for each <option> element.
//The value prop is set to the option value for each <option> element.
//The option value is rendered as the text content of the <option> element.
//Wraps the Select component in React.forwardRef
// forwardRef is used to forward the ref to the <select> element, allowing parent components(any component that uses the Select component as part of its structure. A "parent component" is simply a React component that renders another component as one of its children.) to interact with it directly.